### ISSUE TITLE
not building on raspberry pi

### ISSUE THREAD

**Issue by vmarks** [oeai/m-audio-usb-midi-fw#1]
Hi, 
I'd like to use midisport with raspberry pi, and I can't seem to get this to build on Raspbian Stretch. I suspect it's not got the right arch in it, but I'm not sure where to make the change. Can you help?

**Comment by oeai** [comment]
looks like a debian 9 fork, any errors there?

**Comment by vmarks** [comment]
Turns out using the old midisport-firmware installed via apt-get worked. Thank you.

**Comment by oeai** [comment]
good to know. gl
